name: learn-github-actions
on:
  schedule:
    - cron:  '1/6 * * * *'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
